version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app

  mysql:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=randompassword
      - MYSQL_DATABASE=question_vault
      - MYSQL_USER=questionvault
      - MYSQL_PASSWORD=randompassword