@baseUrl = http://api.localhost

@email = tnowad@gmail.com
@password = password
@accessTokenName = access_token
@accessTokenValue = <accessToken>
@refreshTokenName = refresh_token
@refreshTokenValue = <refreshToken>

### Register User ###
# @name register
POST {{baseUrl}}/api/auth/register
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

### Login User ###
# @name login
POST {{baseUrl}}/api/auth/login
Cookie: access
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

### Refresh Token ###
# @name refresh-token
POST {{baseUrl}}/api/auth/refresh-token
Cookie: refresh_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY4ODUzNzA2NCwiZXhwIjoxNjg5MTQxODY0fQ.9LA85I8qG72V2dthIsJ5c69-lHZQ4UCDQKzN2GY_gQE
Content-Type: application/javascript