@baseUrl = http://api.localhost

@email = tnowad@gmail.com
@password = password

### Register User ###
# @name register
POST {{baseUrl}}/api/auth/register
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

### Login User ###
# @name login
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}